#!/bin/bash

channel=3
path="/$2/cell_segmentation/$1/CH$channel"
count=0
files_to_process=()
for file in "$path"/*;
do
  file=$(basename "$file")
#   if ! (ls "$path/$file" | grep -q 'extracted_cells'); then
  files_to_process+=("$file")
#   fi
done

(
for file in "${files_to_process[@]}"
do
   echo $file
   ((i=i%10)); ((i++==0)) && wait
   python /scratch/programming/preprocessing-pipeline/in_development/Will/cell_extractor/scripts/create_example_for_one_section.py --animal "$1" --section "$file" --disk "$2"&
done
)

