#!/bin/bash

channel=3
root="/$2/cell_segmentation/$1"

calculate_features(){
path="$root/CH$channel"
count=0

files_to_process=()
for file in "$path"/*;
do
  file=$(basename "$file")
  if ! (ls "$path/$file" | grep -q 'puntas'); then
     files_to_process+=("$file")
  fi
done

echo "${files_to_process[*]}"
(
for file in "${files_to_process[@]}"
do
   ((i=i%10)); ((i++==0)) && wait
   python /data/programming/pipeline/in_development/Will/cell_extractor/scripts/calculate_features_for_one_section.py --animal "$1" --section "$file" --disk "$2"&
done
)
}

if ls "$root" | grep -q 'average_cell_image.pkl'; then
   calculate_features
fi

